# Generated by Django 5.2.9

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_organisationissue_expiration_date_and_more"),
        ("iam", "0019_add_view_globalsettings_in_custom_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMethodState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(default=dict)),
                (
                    "folder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_method_state",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "db_table": "core_custommethodstate",
            },
        ),
    ]
